### ISSUE TITLE
Deciding when to initiate discriminator loss to kick in

### ISSUE THREAD

**Issue by snoop2head** [CompVis/taming-transformers#129]
It seems like disc_start is numbers of steps when discriminator loss kicks in during the training, according to #93 and according to the code in taming/modules/losses/vqperceptual.py

**First question is, What will be the recommended steps or epochs for discriminator_iter_start? ** 

**Second question is, shouldn't it be better to set as relative percentage of the total steps for training rather than absolute value of steps?** 

Below is part of configs/custom_vqgan.yaml file with default values, FIY
```
lossconfig:
  target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
  params:
    disc_conditional: False
    disc_in_channels: 3
    disc_start: 10000 # 10000 steps
    disc_weight: 0.8
    codebook_weight: 1.0
```
