### ISSUE TITLE
epoch

### ISSUE THREAD

**Issue by fido20160817** [CompVis/taming-transformers#159]
where to set max epoch. The code is too implicit for me to follow...

**Comment by joanrod** [comment]
It is set to 1000 by default by pytorch lightning. You need to set it in the .yaml file, with something like:
```
lightning:
    trainer:
        (...)
        max_epochs: 2000
```
