### ISSUE TITLE
config for conditional training?

### ISSUE THREAD

**Issue by entangledothers** [CompVis/taming-transformers#68]
I'm trying to figure out how to train a conditional model, but am a little stumped as to the correct way to setup the config, my data structure looks this:

**root_folder**
-- _category_01_folder_
-- _category_02_folder_
-- _category_03_folder_
_... etc._

My question is how do I format the config, say from the custom_vqgan config file to train this as a conditional model, and additionally, the text files we should generate for train and test, how are they formatted in this regard?

Thanks in advance for any help!

**Comment by areiner-novetta** [comment]
I came here looking for this as well.  I started to adapt the config from the conditional image net (CIN) model linked in the README, which looks like this:

```
model:
  ...
  params:
    first_stage_key: image
    cond_stage_key: class_label
    ...
    cond_stage_config:
      target: taming.modules.util.Labelator
      params:
        n_classes: 1000
```

However, it's not clear how the labels for each image are supposed to be supplied during training and sampling.
